name: 🔧 Refacto ou nettoyage
description: Amélioration du code sans changement de fonctionnalité
title: "[REFACTO] : "
labels: [refactor]
body:
  - type: textarea
    id: zone_concernee
    attributes:
      label: Quelle partie du code est concernée ?
      placeholder: "Description de la partie du code concernée"
    validations:
      required: true

  - type: textarea
    id: objectif
    attributes:
      label: Objectif du refacto
      placeholder: "Description de l'objectif du refacto"
    validations:
      required: true